/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IDividendPayingTokenInterface extends ethers.utils.Interface {
  functions: {
    "distributeDividends()": FunctionFragment;
    "dividendOf(address)": FunctionFragment;
    "withdrawDividend()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "distributeDividends",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "dividendOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "withdrawDividend",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "distributeDividends",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dividendOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawDividend",
    data: BytesLike
  ): Result;

  events: {
    "DividendWithdrawn(address,uint256)": EventFragment;
    "DividendsDistributed(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DividendWithdrawn"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DividendsDistributed"): EventFragment;
}

export class IDividendPayingToken extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IDividendPayingTokenInterface;

  functions: {
    distributeDividends(
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "distributeDividends()"(
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    dividendOf(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "dividendOf(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    withdrawDividend(overrides?: Overrides): Promise<ContractTransaction>;

    "withdrawDividend()"(overrides?: Overrides): Promise<ContractTransaction>;
  };

  distributeDividends(
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "distributeDividends()"(
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  dividendOf(_owner: string, overrides?: CallOverrides): Promise<BigNumber>;

  "dividendOf(address)"(
    _owner: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  withdrawDividend(overrides?: Overrides): Promise<ContractTransaction>;

  "withdrawDividend()"(overrides?: Overrides): Promise<ContractTransaction>;

  callStatic: {
    distributeDividends(overrides?: CallOverrides): Promise<void>;

    "distributeDividends()"(overrides?: CallOverrides): Promise<void>;

    dividendOf(_owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "dividendOf(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawDividend(overrides?: CallOverrides): Promise<void>;

    "withdrawDividend()"(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    DividendWithdrawn(to: string | null, weiAmount: null): EventFilter;

    DividendsDistributed(from: string | null, weiAmount: null): EventFilter;
  };

  estimateGas: {
    distributeDividends(overrides?: PayableOverrides): Promise<BigNumber>;

    "distributeDividends()"(overrides?: PayableOverrides): Promise<BigNumber>;

    dividendOf(_owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "dividendOf(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    withdrawDividend(overrides?: Overrides): Promise<BigNumber>;

    "withdrawDividend()"(overrides?: Overrides): Promise<BigNumber>;
  };

  populateTransaction: {
    distributeDividends(
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "distributeDividends()"(
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    dividendOf(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "dividendOf(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdrawDividend(overrides?: Overrides): Promise<PopulatedTransaction>;

    "withdrawDividend()"(overrides?: Overrides): Promise<PopulatedTransaction>;
  };
}
